### ISSUE TITLE
[Bug]: not compatible with the latest version 1.19.4

### ISSUE THREAD

**Issue by MissGamerz** [ixDarkLorD/ModpackManager#4]
### Describe the Bug

crashes on 1.19.4

### To Reproduce

start minecraft in 1.19.4 with this mod

### OS

win11

### Minecraft Version

1.19.2

### ModLoader

Fabric

### Mod Version

latest

**Comment by ixDarkLorD** [comment]
I've never released the 1.19.4 version of this mod yet, but I'm working on it. ✨
