### ISSUE TITLE
[Feature]: Don't force override the window title

### ISSUE THREAD

**Issue by SplendidAlakey** [ixDarkLorD/ModpackManager#5]
### What feature do you want to see in the upcoming releases?

Currently, the mod completely overrides the window title to the modpack's name.

The reason why I don't want to override the title name is because Sodium implements title window checks for Nvidia users to avoid crashes with certain drivers.

**Comment by ixDarkLorD** [comment]
I've added a new safe mode option in the config file.
Thank you for submitting the report❤️
