### ISSUE TITLE
[Bug]: Wrong loader information

### ISSUE THREAD

**Issue by SplendidAlakey** [ixDarkLorD/ModpackManager#6]
### Describe the Bug

The loader information in the bottom left corner seems to be just hardcoded to display "Fabric Loader 0.14.13", instead of the actual loader.

### To Reproduce

1. Install the mod with Fabric Loader 0.14.19
2. Launch the game and check the bottom left corner info - it shows Fabric Loader 0.14.13
3. Uninstall Fabric Loader and install [Quilt Loader](https://quiltmc.org) 0.18.10, which provides Fabric Loader 0.14.19 bridges
4. Launch the game and check the bottom left corner info again - it still shows Fabric Loader 0.14.13, even though we aren't even on Fabric anymore

### Catch the bug In Action!

With the mod:
![2023-05-16_13 25 41](https://github.com/ixDarkLorD/ModpackManager/assets/86702831/7da53446-4723-49ce-865d-b75f5011b5fc)

Without the mod: 
Fabric
![2023-05-16_13 53 04](https://github.com/ixDarkLorD/ModpackManager/assets/86702831/f0512dae-b3fa-4fcd-a13b-420a01c2b776)

Quilt
![2023-05-16_13 37 06](https://github.com/ixDarkLorD/ModpackManager/assets/86702831/88556089-b5e0-4013-966b-8c7658800444)

### Crash Report or Log

https://gist.github.com/SplendidAlakey/0717f1dabaf76a04ab3d1a1b3f8d5595

### OS

Windows 10

### Minecraft Version

1.19.2

### ModLoader

Fabric

### Mod Version

0.2.2

**Comment by ixDarkLorD** [comment]
I solved it 👍
