### ISSUE TITLE
[Bug]: Crash with FancyMenu

### ISSUE THREAD

**Issue by SplendidAlakey** [ixDarkLorD/ModpackManager#7]
### Describe the Bug

The game crashes on startup, when Modpack Manager is installed together with FancyMenu.

### To Reproduce

1. Install FancyMenu and Modpack Manager
2. Launch the game and crash

### Crash Report or Log

https://gist.github.com/SplendidAlakey/5163f9d5700d495d1bc97a42da483443

### OS

Windows 10

### Minecraft Version

1.19.2

### ModLoader

Fabric

### Mod Version

0.2.2

**Comment by ixDarkLorD** [comment]
I solved it 👍
